import Foundation

// MARK: - ClipboardRetentionPolicy

/// Pure policy rules for clipboard retention and pruning
public struct ClipboardRetentionPolicy: Sendable {
    private static let concealedMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    private let exclusionRules: [ExclusionRule]
    private let ignoredTextPatterns: [String]
    private let historyLimit: Int
    private let maxPayloadSizeBytes: Int

    public init(
        exclusionRules: [ExclusionRule] = [],
        ignoredTextPatterns: [String] = [],
        historyLimit: Int = 100,
        maxPayloadSizeBytes: Int = 10 * 1024 * 1024
    ) {
        self.exclusionRules = exclusionRules
        self.ignoredTextPatterns = ignoredTextPatterns
        self.historyLimit = historyLimit
        self.maxPayloadSizeBytes = maxPayloadSizeBytes
    }

    public func decide(_ candidate: CapturedClipboardContent, existing: [ClipboardItem]) -> RetentionDecision {
        if !candidate.pasteboardTypeMarkers.isDisjoint(with: Self.concealedMarkers) {
            return .skip
        }
        if let sourceBundleID = candidate.sourceBundleID,
           exclusionRules.contains(where: { $0.bundleID == sourceBundleID }) {
            return .skip
        }
        if let text = candidate.textContent,
           ignoredTextPatterns.contains(where: { pattern in
               (try? NSRegularExpression(pattern: pattern))?.firstMatch(
                   in: text, range: NSRange(text.startIndex..., in: text)
               ) != nil
           }) {
            return .skip
        }
        if let match = existing.first(where: { $0.contentHash == candidate.contentHash }) {
            return .bumpExisting(itemID: match.id)
        }
        if candidate.payloadSizeBytes > maxPayloadSizeBytes {
            return .retainMetadataOnly
        }
        return .retainFull
    }

    public func itemsToPrune(existing: [ClipboardItem]) -> [UUID] {
        let unpinned = existing.filter { !$0.isPinned }
        guard unpinned.count > historyLimit else { return [] }
        let excessCount = unpinned.count - historyLimit
        return unpinned
            .sorted { $0.capturedAt < $1.capturedAt }
            .prefix(excessCount)
            .map(\.id)
    }
}
