// Dumps every static table of the original engine as Rust source.
// Linking against the real objects means the tables cannot drift from
// the C++ source: there is no text parsing anywhere in this path.
#include <stdio.h>
#include "keycons.h"
#include "vnlexi.h"
#include "inputproc.h"
#include "charset.h"

// Structures are defined inside ukengine.cpp, redeclared identically here.
struct VowelSeqInfo {
    int len, complete, conSuffix;
    VnLexiName v[3];
    VowelSeq sub[3];
    int roofPos;
    VowelSeq withRoof;
    int hookPos;
    VowelSeq withHook;
};
struct ConSeqInfo { int len; VnLexiName c[3]; bool suffix; };
struct VCPair { VowelSeq v; ConSeq c; };

extern VowelSeqInfo VSeqList[];
extern ConSeqInfo CSeqList[];
extern VCPair VCPairList[];
extern UkCharType UkcMap[256];
extern VnLexiName IsoVnLexiMap[256];
extern StdVnChar IsoStdVnCharMap[256];
extern bool IsVnVowel[];
extern int StdVnNoTone[TOTAL_VNCHARS];
extern int StdVnRootChar[TOTAL_VNCHARS];
extern UnicodeChar UnicodeTable[TOTAL_VNCHARS];
extern UKDWORD VIQRTable[TOTAL_VNCHARS];
extern UKDWORD UnicodeComposite[TOTAL_VNCHARS];
extern UKWORD WinCP1258[TOTAL_VNCHARS];
extern UKWORD WinCP1258Pre[TOTAL_VNCHARS];
extern unsigned char SingleByteTables[][TOTAL_VNCHARS];
extern UKWORD DoubleByteTables[][TOTAL_VNCHARS];
void SetupUnikeyEngine();
void engineClassInit();

#define VS_COUNT 70
#define CS_COUNT 30
#define VC_COUNT 153
#define SINGLE_COUNT 6
#define DOUBLE_COUNT 4

static void row(const char *fmt) { (void)fmt; }

static void dumpKeyMap(const char *name, UkKeyMapping *m)
{
    printf("pub const %s: &[(u8, u16)] = &[\n   ", name);
    for (int i = 0; m[i].key; i++)
        printf(" (%u, %d),", (unsigned)m[i].key, m[i].action);
    printf("\n];\n\n");
}

int main()
{
    SetupUnikeyEngine();
    engineClassInit();

    printf("// @generated by port/tablegen/dump.cpp from the original C++ engine.\n");
    printf("// Do not edit by hand. Regenerate with: make -C port/tablegen\n\n");
    printf("use crate::lexi::{Lexi, VSeq};\n\n");

    printf("pub const VSEQ_COUNT: usize = %d;\n", VS_COUNT);
    printf("pub const CSEQ_COUNT: usize = %d;\n\n", CS_COUNT);

    printf("#[derive(Clone, Copy)]\npub struct VSeqInfo {\n");
    printf("    pub len: u8,\n    pub complete: bool,\n    pub con_suffix: bool,\n");
    printf("    pub v: [Lexi; 3],\n    pub sub: [VSeq; 3],\n");
    printf("    pub roof_pos: i8,\n    pub with_roof: VSeq,\n");
    printf("    pub hook_pos: i8,\n    pub with_hook: VSeq,\n}\n\n");

    printf("pub const VSEQ: [VSeqInfo; VSEQ_COUNT] = [\n");
    for (int i = 0; i < VS_COUNT; i++) {
        VowelSeqInfo &e = VSeqList[i];
        printf("    VSeqInfo { len: %d, complete: %s, con_suffix: %s, "
               "v: [Lexi(%d), Lexi(%d), Lexi(%d)], sub: [VSeq(%d), VSeq(%d), VSeq(%d)], "
               "roof_pos: %d, with_roof: VSeq(%d), hook_pos: %d, with_hook: VSeq(%d) },\n",
               e.len, e.complete ? "true" : "false", e.conSuffix ? "true" : "false",
               (int)e.v[0], (int)e.v[1], (int)e.v[2],
               (int)e.sub[0], (int)e.sub[1], (int)e.sub[2],
               e.roofPos, (int)e.withRoof, e.hookPos, (int)e.withHook);
    }
    printf("];\n\n");

    printf("#[derive(Clone, Copy)]\npub struct CSeqInfo {\n");
    printf("    pub len: u8,\n    pub c: [Lexi; 3],\n    pub suffix: bool,\n}\n\n");
    printf("pub const CSEQ: [CSeqInfo; CSEQ_COUNT] = [\n");
    for (int i = 0; i < CS_COUNT; i++) {
        ConSeqInfo &e = CSeqList[i];
        printf("    CSeqInfo { len: %d, c: [Lexi(%d), Lexi(%d), Lexi(%d)], suffix: %s },\n",
               e.len, (int)e.c[0], (int)e.c[1], (int)e.c[2], e.suffix ? "true" : "false");
    }
    printf("];\n\n");

    // Valid vowel+consonant suffix pairs, as a bitmap: one u32 per vowel
    // sequence, bit c set when (v, c) is a legal pair. Replaces the
    // 153 entry sorted array and its bsearch with a single AND.
    unsigned int bits[VS_COUNT];
    for (int i = 0; i < VS_COUNT; i++) bits[i] = 0;
    for (int i = 0; i < VC_COUNT; i++)
        bits[(int)VCPairList[i].v] |= 1u << (int)VCPairList[i].c;
    printf("pub const VC_VALID: [u32; VSEQ_COUNT] = [\n   ");
    for (int i = 0; i < VS_COUNT; i++) {
        printf(" 0x%08X,", bits[i]);
        if (i % 6 == 5) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const UKC_MAP: [u8; 256] = [\n   ");
    for (int i = 0; i < 256; i++) {
        printf(" %d,", (int)UkcMap[i]);
        if (i % 16 == 15) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const ISO_LEXI: [i16; 256] = [\n   ");
    for (int i = 0; i < 256; i++) {
        printf(" %d,", (int)IsoVnLexiMap[i]);
        if (i % 16 == 15) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const ISO_STD: [u32; 256] = [\n   ");
    for (int i = 0; i < 256; i++) {
        printf(" 0x%X,", (unsigned)IsoStdVnCharMap[i]);
        if (i % 12 == 11) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const IS_VOWEL: [bool; %d] = [\n   ", (int)vnl_lastChar);
    for (int i = 0; i < (int)vnl_lastChar; i++) {
        printf(" %s,", IsVnVowel[i] ? "true" : "false");
        if (i % 8 == 7) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const TOTAL_VNCHARS: usize = %d;\n", TOTAL_VNCHARS);
    printf("pub const TOTAL_ALPHA_VNCHARS: usize = %d;\n\n", TOTAL_ALPHA_VNCHARS);

    printf("pub const STD_NO_TONE: [u16; TOTAL_VNCHARS] = [\n   ");
    for (int i = 0; i < TOTAL_VNCHARS; i++) {
        printf(" %d,", StdVnNoTone[i]);
        if (i % 12 == 11) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const STD_ROOT: [u16; TOTAL_VNCHARS] = [\n   ");
    for (int i = 0; i < TOTAL_VNCHARS; i++) {
        printf(" %d,", StdVnRootChar[i]);
        if (i % 12 == 11) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const UNICODE_TABLE: [u16; TOTAL_VNCHARS] = [\n   ");
    for (int i = 0; i < TOTAL_VNCHARS; i++) {
        printf(" 0x%04X,", (unsigned)UnicodeTable[i]);
        if (i % 10 == 9) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const VIQR_TABLE: [u32; TOTAL_VNCHARS] = [\n   ");
    for (int i = 0; i < TOTAL_VNCHARS; i++) {
        printf(" 0x%08X,", (unsigned)VIQRTable[i]);
        if (i % 8 == 7) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const UNICODE_COMPOSITE: [u32; TOTAL_VNCHARS] = [\n   ");
    for (int i = 0; i < TOTAL_VNCHARS; i++) {
        printf(" 0x%08X,", (unsigned)UnicodeComposite[i]);
        if (i % 8 == 7) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const WIN_CP1258: [u16; TOTAL_VNCHARS] = [\n   ");
    for (int i = 0; i < TOTAL_VNCHARS; i++) {
        printf(" 0x%04X,", (unsigned)WinCP1258[i]);
        if (i % 10 == 9) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const WIN_CP1258_PRE: [u16; TOTAL_VNCHARS] = [\n   ");
    for (int i = 0; i < TOTAL_VNCHARS; i++) {
        printf(" 0x%04X,", (unsigned)WinCP1258Pre[i]);
        if (i % 10 == 9) printf("\n   ");
    }
    printf("\n];\n\n");

    printf("pub const SINGLE_BYTE_TABLES: [[u8; TOTAL_VNCHARS]; %d] = [\n", SINGLE_COUNT);
    for (int t = 0; t < SINGLE_COUNT; t++) {
        printf("    [\n       ");
        for (int i = 0; i < TOTAL_VNCHARS; i++) {
            printf(" 0x%02X,", (unsigned)SingleByteTables[t][i]);
            if (i % 12 == 11) printf("\n       ");
        }
        printf("\n    ],\n");
    }
    printf("];\n\n");

    printf("pub const DOUBLE_BYTE_TABLES: [[u16; TOTAL_VNCHARS]; %d] = [\n", DOUBLE_COUNT);
    for (int t = 0; t < DOUBLE_COUNT; t++) {
        printf("    [\n       ");
        for (int i = 0; i < TOTAL_VNCHARS; i++) {
            printf(" 0x%04X,", (unsigned)DoubleByteTables[t][i]);
            if (i % 10 == 9) printf("\n       ");
        }
        printf("\n    ],\n");
    }
    printf("];\n\n");

    // Packed lookup keys, sorted at generation time so the engine can
    // binary search a flat u32 array instead of running qsort at start
    // up and bsearch through a comparator function pointer.
    {
        struct KV { unsigned int key; int idx; };
        KV vk[VS_COUNT], ck[CS_COUNT];
        for (int i = 0; i < VS_COUNT; i++) {
            VowelSeqInfo &e = VSeqList[i];
            vk[i].key = (((unsigned)(e.v[0] + 1)) << 16)
                      | (((unsigned)(e.v[1] + 1)) << 8)
                      |   (unsigned)(e.v[2] + 1);
            vk[i].idx = i;
        }
        for (int i = 0; i < CS_COUNT; i++) {
            ConSeqInfo &e = CSeqList[i];
            ck[i].key = (((unsigned)(e.c[0] + 1)) << 16)
                      | (((unsigned)(e.c[1] + 1)) << 8)
                      |   (unsigned)(e.c[2] + 1);
            ck[i].idx = i;
        }
        for (int i = 1; i < VS_COUNT; i++)
            for (int j = i; j > 0 && vk[j-1].key > vk[j].key; j--) {
                KV t = vk[j-1]; vk[j-1] = vk[j]; vk[j] = t;
            }
        for (int i = 1; i < CS_COUNT; i++)
            for (int j = i; j > 0 && ck[j-1].key > ck[j].key; j--) {
                KV t = ck[j-1]; ck[j-1] = ck[j]; ck[j] = t;
            }
        printf("pub const VSEQ_KEYS: [u32; VSEQ_COUNT] = [\n   ");
        for (int i = 0; i < VS_COUNT; i++) {
            printf(" 0x%06X,", vk[i].key);
            if (i % 8 == 7) printf("\n   ");
        }
        printf("\n];\n\n");
        printf("pub const VSEQ_IDX: [u8; VSEQ_COUNT] = [\n   ");
        for (int i = 0; i < VS_COUNT; i++) {
            printf(" %d,", vk[i].idx);
            if (i % 16 == 15) printf("\n   ");
        }
        printf("\n];\n\n");
        printf("pub const CSEQ_KEYS: [u32; CSEQ_COUNT] = [\n   ");
        for (int i = 0; i < CS_COUNT; i++) {
            printf(" 0x%06X,", ck[i].key);
            if (i % 8 == 7) printf("\n   ");
        }
        printf("\n];\n\n");
        printf("pub const CSEQ_IDX: [u8; CSEQ_COUNT] = [\n   ");
        for (int i = 0; i < CS_COUNT; i++) {
            printf(" %d,", ck[i].idx);
            if (i % 16 == 15) printf("\n   ");
        }
        printf("\n];\n\n");
    }

    dumpKeyMap("TELEX_MAP", TelexMethodMapping);
    dumpKeyMap("SIMPLE_TELEX_MAP", SimpleTelexMethodMapping);
    dumpKeyMap("VNI_MAP", VniMethodMapping);
    dumpKeyMap("VIQR_MAP", VIQRMethodMapping);
    dumpKeyMap("MSVI_MAP", MsViMethodMapping);
    return 0;
}
