import CoreGraphics
import Foundation

// MARK: - TypingPipeline

/// Coordinates the multi-stage event processing pipeline:
/// 1. Loop-back avoidance (marker filter)
/// 2. Mouse click buffer reset (Left, Right, Other)
/// 3. Pass through non-keyboard & solo modifiers
/// 4. Pass through Hotkey combinations (Cmd+Key, Ctrl+Key, Option+Key)
/// 5. Language bypass (0 cost when Vietnamese mode is OFF)
/// 6. KeyUp pass-through
/// 7. Fast-paths (Fn/Media, Navigation, Backspace, WordBreaks)
/// 8. Composing engine & speculative context re-composition
public final class TypingPipeline {
    // MARK: - State

    public let engine: SKeyEngine
    private let languageProvider: () -> Bool
    private let onToggleLanguage: () -> Void

    // MARK: - Init

    public init(
        engine: SKeyEngine = SKeyEngine(),
        languageProvider: @escaping () -> Bool = { PreferencesService.shared.isVietnamese },
        onToggleLanguage: @escaping () -> Void = {}
    ) {
        self.engine = engine
        self.languageProvider = languageProvider
        self.onToggleLanguage = onToggleLanguage
    }

    // MARK: - Processing Pipeline

    public func process(event: CGEvent, type: CGEventType) -> InterceptorResult {
        // Stage 1: Skip synthetic events generated by SKey itself
        if event.getIntegerValueField(.eventSourceUserData) == KeyConstants.eventMarker {
            return .passThrough
        }

        // Stage 2: Mouse clicks reset buffer and pass through immediately
        if type == .leftMouseDown || type == .rightMouseDown || type == .otherMouseDown {
            engine.reset()
            return .passThrough
        }

        // Stage 3: Pass through non-keyboard events
        guard type == .keyDown || type == .keyUp || type == .flagsChanged else {
            return .passThrough
        }

        // Stage 4: Pass through modifier keys pressed alone
        if type == .flagsChanged {
            return .passThrough
        }

        let keyCode = CGKeyCode(event.getIntegerValueField(.keyboardEventKeycode))
        let flags   = event.flags

        // Stage 5: Pass through Hotkey combinations (Cmd+Key, Ctrl+Key, Option+Key)
        let isCommand = flags.contains(.maskCommand)
        let isControl = flags.contains(.maskControl)
        let isOption  = flags.contains(.maskAlternate)

        // Hotkey: Option + Z toggles language mode
        if isOption && !isCommand && !isControl && keyCode == KeyConstants.kVK_ANSI_Z {
            if type == .keyDown {
                onToggleLanguage()
            }
            return .swallowed
        }

        if isCommand || isControl || isOption {
            engine.reset()
            return .passThrough
        }

        // Stage 6: Pass through if Vietnamese mode is OFF (0-overhead bypass)
        guard languageProvider() else {
            return .passThrough
        }

        // Stage 7: KeyUp events - pass through and keep engine state
        if type == .keyUp {
            return .passThrough
        }

        // Stage 8: KeyDown composing engine
        return handleKeyDown(keyCode: keyCode, flags: flags, event: event)
    }

    // MARK: - Composing Engine Handling

    private func handleKeyDown(keyCode: CGKeyCode, flags: CGEventFlags, event: CGEvent) -> InterceptorResult {
        let category = KeyClassifier.classify(keyCode: keyCode)

        // Fast-path 1: Function & Media keys (F1-F20, Volume, Brightness) pass through untouched
        if category == .functionOrMedia {
            return .passThrough
        }

        // Fast-path 2: Navigation keys (Arrows, Home, End, Esc, ForwardDelete) reset buffer & pass through
        if category == .navigation {
            engine.reset()
            return .passThrough
        }

        // Sync caps state for typing
        engine.setCapsState(
            shiftPressed: flags.contains(.maskShift),
            capsLockOn:   flags.contains(.maskAlphaShift)
        )

        // Fast-path 3: Backspace key (0x33)
        if category == .backspace {
            let res = engine.backspace()
            if res.handled {
                var backspaces = res.backspaces
                if backspaces > 0 && !AccessibilityContextReader.isSpotlightActive() && AccessibilityContextReader.shared.hasActiveSelection() {
                    backspaces += 1
                }
                KeyEventSender.shared.inject(backspaces: backspaces, text: res.text)
                return .swallowed
            }
            return .passThrough
        }

        // Fast-path 4: Structural word-break keys (Return, Tab, KeypadEnter)
        if category == .wordBreak && keyCode != KeyConstants.kVK_Space {
            engine.reset()
            return .passThrough
        }

        // Printable characters & Space (Word-break with engine evaluation)
        var charCode: UInt32 = 0
        var hasValidChar = false
        withUnsafeTemporaryAllocation(of: UniChar.self, capacity: 4) { buffer in
            guard let basePtr = buffer.baseAddress else { return }
            var len = 0
            event.keyboardGetUnicodeString(maxStringLength: 4, actualStringLength: &len, unicodeString: basePtr)
            if len > 0 {
                charCode = UInt32(basePtr[0])
                hasValidChar = true
            }
        }
        guard hasValidChar else { return .passThrough }

        #if DEBUG
        skeyLog("KeyDown: code=\(keyCode), char='\(UnicodeScalar(charCode) ?? " ")'(\(charCode))", category: .keyboard)
        #endif

        // Filter printable ASCII range (Space 32 to ~ 126)
        if (32...126).contains(charCode) {
            let res = engine.filter(character: charCode)
            if res.handled {
                var backspaces = res.backspaces
                if backspaces > 0 && !AccessibilityContextReader.isSpotlightActive() && AccessibilityContextReader.shared.hasActiveSelection() {
                    backspaces += 1
                }
                #if DEBUG
                skeyLog("Typing transform: '\(UnicodeScalar(charCode) ?? " ")' -> bs=\(backspaces) '\(res.text)'", category: .keyboard)
                #endif
                KeyEventSender.shared.inject(backspaces: backspaces, text: res.text)
                return .swallowed
            } else {
                #if DEBUG
                skeyLog("Engine unhandled '\(UnicodeScalar(charCode) ?? " ")', trying context recompose", category: .keyboard)
                #endif
                // Smart Context Re-composition: if normal engine did not transform,
                // check if the caret is placed behind an existing committed word (e.g. "đáu" + "a" -> "đấu")
                if ContextRecomposer.shared.tryRecompose(charCode: charCode, engine: engine) {
                    return .swallowed
                }
            }
        } else {
            engine.reset()
        }

        return .passThrough
    }
}
