import Cocoa

// MARK: - TypingPipeline

/// Production multi-stage event processing pipeline.
/// Optimized for $0\mu\text{s}$ latency with strict separation of hotkeys, navigation, composing, and macro expansion.
public final class TypingPipeline {
    private let engine: SKeyEngine
    private let languageProvider: () -> Bool
    private let onToggleLanguage: () -> Void

    /// Tracks whether caret may have moved due to navigation, selection, or app focus
    private var caretMayHaveMoved = false

    public init(
        engine: SKeyEngine,
        languageProvider: @escaping () -> Bool,
        onToggleLanguage: @escaping () -> Void
    ) {
        self.engine = engine
        self.languageProvider = languageProvider
        self.onToggleLanguage = onToggleLanguage
    }

    // MARK: - Pipeline Entry Point

    public func process(event: CGEvent, type: CGEventType) -> InterceptorResult {
        // Stage 1: Pass through synthetic events generated by SKey
        if event.getIntegerValueField(.eventSourceUserData) == KeyConstants.eventMarker {
            return .passThrough
        }

        // Stage 2: Pass through null tap / disabled events
        if type == .tapDisabledByTimeout || type == .tapDisabledByUserInput {
            return .passThrough
        }

        // Stage 3: Handle Mouse Clicks (User clicked mouse to reposition caret or switch focus)
        if type == .leftMouseDown || type == .rightMouseDown || type == .otherMouseDown {
            engine.reset()
            MacroEngine.shared.reset()
            caretMayHaveMoved = true
            return .passThrough
        }

        // Pass through non-keyboard events
        guard type == .keyDown || type == .keyUp || type == .flagsChanged else {
            return .passThrough
        }

        // Stage 4: Pass through modifier keys pressed alone
        if type == .flagsChanged {
            return .passThrough
        }

        let keyCode = CGKeyCode(event.getIntegerValueField(.keyboardEventKeycode))
        let flags   = event.flags

        // Stage 5: Pass through Hotkey combinations (Cmd+Key, Ctrl+Key, Option+Key)
        let isCommand = flags.contains(.maskCommand)
        let isControl = flags.contains(.maskControl)
        let isOption  = flags.contains(.maskAlternate)

        // Hotkey: Option + Z toggles language mode
        if isOption && !isCommand && !isControl && keyCode == KeyConstants.kVK_ANSI_Z {
            if type == .keyDown {
                onToggleLanguage()
            }
            return .swallowed
        }

        // Hotkey: Option + V toggles Clipboard History Popup
        if isOption && !isCommand && !isControl && keyCode == KeyConstants.kVK_ANSI_V {
            if type == .keyDown {
                DispatchQueue.main.async {
                    ClipboardFeature.shared.togglePopup()
                }
            }
            return .swallowed
        }

        if isCommand || isControl || isOption {
            engine.reset()
            MacroEngine.shared.reset()
            caretMayHaveMoved = false
            return .passThrough
        }

        // Stage 6: KeyUp events - pass through and keep engine state
        if type == .keyUp {
            return .passThrough
        }

        let isVn = languageProvider()

        // Stage 7: English mode handling (With optional Macro Expansion)
        if !isVn {
            if AppSettings.shared.macro.isEnabled && AppSettings.shared.macro.inEnglishMode {
                return handleEnglishMacroKeyDown(keyCode: keyCode, flags: flags, event: event)
            }
            return .passThrough
        }

        // Stage 8: KeyDown composing engine
        return handleKeyDown(keyCode: keyCode, flags: flags, event: event)
    }

    // MARK: - Composing Engine Handling

    private func handleKeyDown(keyCode: CGKeyCode, flags: CGEventFlags, event: CGEvent) -> InterceptorResult {
        let category = KeyClassifier.classify(keyCode: keyCode)

        // Fast-path 1: Function & Media keys (F1-F20, Volume, Brightness) pass through untouched
        if category == .functionOrMedia {
            return .passThrough
        }

        // Fast-path 2: Navigation keys (Arrows, Home, End, ForwardDelete) reset buffer & mark caret movement
        if category == .navigation {
            engine.reset()
            MacroEngine.shared.reset()
            caretMayHaveMoved = (keyCode != KeyConstants.kVK_Escape)
            return .passThrough
        }

        // Sync caps state for typing
        engine.setCapsState(
            shiftPressed: flags.contains(.maskShift),
            capsLockOn:   flags.contains(.maskAlphaShift)
        )

        // Fast-path 3: Backspace key (0x33)
        if category == .backspace {
            MacroEngine.shared.recordBackspace()
            let res = engine.backspace()
            if res.handled {
                caretMayHaveMoved = false
                let bs = resolveBackspaces(res.backspaces)
                KeyEventSender.shared.inject(backspaces: bs, text: res.text)
                return .swallowed
            }
            caretMayHaveMoved = false
            return .passThrough
        }

        // Fast-path 4: Structural word-break keys (Return, Tab, KeypadEnter)
        if category == .wordBreak && keyCode != KeyConstants.kVK_Space {
            engine.reset()
            MacroEngine.shared.reset()
            caretMayHaveMoved = false
            return .passThrough
        }

        // Printable characters & Space (Word-break with engine evaluation)
        var charCode: UInt32 = 0
        var hasValidChar = false
        withUnsafeTemporaryAllocation(of: UniChar.self, capacity: 4) { buffer in
            guard let basePtr = buffer.baseAddress else { return }
            var len = 0
            event.keyboardGetUnicodeString(maxStringLength: 4, actualStringLength: &len, unicodeString: basePtr)
            if len > 0 {
                charCode = UInt32(basePtr[0])
                hasValidChar = true
            }
        }
        guard hasValidChar else { return .passThrough }

        // Filter printable ASCII range (Space 32 to ~ 126)
        if (32...126).contains(charCode) {
            // Check Space for Macro Expansion
            if keyCode == KeyConstants.kVK_Space {
                let macroRes = MacroEngine.shared.evaluateMacroOnSpace()
                if macroRes.handled {
                    engine.reset()
                    caretMayHaveMoved = false
                    let bs = resolveBackspaces(macroRes.backspaces)
                    KeyEventSender.shared.inject(backspaces: bs, text: macroRes.replacement)
                    return .swallowed
                }
            }

            let res = engine.filter(character: charCode)
            if res.handled {
                caretMayHaveMoved = false
                let bs = resolveBackspaces(res.backspaces)
                #if DEBUG
                skeyLog("Typing transform: '\(UnicodeScalar(charCode) ?? " ")' -> bs=\(bs) '\(res.text)'", category: .keyboard)
                #endif
                if let scalar = UnicodeScalar(charCode) {
                    MacroEngine.shared.recordChar(Character(scalar))
                }
                KeyEventSender.shared.inject(backspaces: bs, text: res.text)
                return .swallowed
            } else {
                if let scalar = UnicodeScalar(charCode) {
                    MacroEngine.shared.recordChar(Character(scalar))
                }

                // Smart Context Re-composition:
                // Evaluated ONLY when caret was explicitly repositioned via Navigation keys (Arrows/Home/End)
                if caretMayHaveMoved && ContextRecomposer.shared.tryRecompose(charCode: charCode, engine: engine) {
                    caretMayHaveMoved = false
                    return .swallowed
                }
                caretMayHaveMoved = false
            }
        } else {
            engine.reset()
            MacroEngine.shared.reset()
            caretMayHaveMoved = false
        }

        return .passThrough
    }

    // MARK: - English Mode Macro Handling

    private func handleEnglishMacroKeyDown(keyCode: CGKeyCode, flags: CGEventFlags, event: CGEvent) -> InterceptorResult {
        let category = KeyClassifier.classify(keyCode: keyCode)

        if category == .navigation || category == .functionOrMedia {
            MacroEngine.shared.reset()
            return .passThrough
        }

        if category == .backspace {
            MacroEngine.shared.recordBackspace()
            return .passThrough
        }

        if category == .wordBreak && keyCode != KeyConstants.kVK_Space {
            MacroEngine.shared.reset()
            return .passThrough
        }

        var charCode: UInt32 = 0
        withUnsafeTemporaryAllocation(of: UniChar.self, capacity: 4) { buffer in
            guard let basePtr = buffer.baseAddress else { return }
            var len = 0
            event.keyboardGetUnicodeString(maxStringLength: 4, actualStringLength: &len, unicodeString: basePtr)
            if len > 0 { charCode = UInt32(basePtr[0]) }
        }

        guard (32...126).contains(charCode) else {
            MacroEngine.shared.reset()
            return .passThrough
        }

        if keyCode == KeyConstants.kVK_Space {
            let macroRes = MacroEngine.shared.evaluateMacroOnSpace()
            if macroRes.handled {
                let bs = resolveBackspaces(macroRes.backspaces)
                KeyEventSender.shared.inject(backspaces: bs, text: macroRes.replacement)
                return .swallowed
            }
            return .passThrough
        }

        if let scalar = UnicodeScalar(charCode) {
            MacroEngine.shared.recordChar(Character(scalar))
        }

        return .passThrough
    }

    // MARK: - Hot Path Utilities

    @inline(__always)
    private func resolveBackspaces(_ count: Int) -> Int {
        guard count > 0 else { return 0 }
        let cat = AppFocusObserver.shared.currentCategory
        // Only check active selection on Web Browsers (Omnibox autocomplete) - 0 IPC for native apps & Spotlight!
        if cat == .webBrowser && AccessibilityContextReader.shared.hasActiveSelection() {
            return count + 1
        }
        return count
    }
}
